import Head from 'next/head'

import { Toolbar, AppBar, Typography, CircularProgress } from '@material-ui/core';
import React from 'react';
import axios from 'axios';

import List from '../components/List'

export default function Home() {

  const [notices, setNotices] = React.useState([])

  React.useEffect(() => {
    axios.get('https://swdbphc.ml/api/notices/feed?start=0&limit=10').then((response) => {
      // console.log(response.data.data)
      setNotices(response.data.data)
    })
  }, [])

  return (
    <div>
      <Head>
        <title>SWD Notices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <AppBar position="static">
          <Toolbar>
            <Typography variant="h6">
              SWD
            </Typography>
          </Toolbar>
        </AppBar>
      </header>

      <main>
        <center>
          {notices ? <List notices={notices} /> : <CircularProgress/>}
        </center>
      </main>

    </div>
  )
}
